### ISSUE TITLE
Deserialize DateTime

### ISSUE THREAD

**Issue by pjcunningham** [thosakwe/json_god#11]
Trying out Dart/Angel and got stuck with deserializing a DateTime. See this snippet:

```
import 'package:json_god/json_god.dart' as god;

class Test {
  DateTime date;
}

void main() {
  //  god.debug = true;

  var test = new Test()
    ..date = new DateTime(2017);

  print(test.date);

  String json = god.serialize(test);
  print(json);

  Test new_test = god.deserialize(json, outputType: Test);
  print(new_test.date);
}
```
Output is:

```
2017-01-01 00:00:00.000
{"date":"2017-01-01T00:00:00.000"}
null
```
Regards, Paul.

**Comment by thosakwe** [comment]
Thanks for the issue. I don't remember if json_god deserializes DateTimes. I don't think it does.

Angel will take care of that for you if you use a TypedService to wrap another service. Here's the wiki page:

A TypedService just uses json_god, but also handles DateTime. Your target class will have to extend "Model," found in package:angel_framework/common.dart.

Regardless, this library is technically still in beta. I've identified several optimizations I can do before releasing the official version, so I'll get this fix done as well.

**Comment by pjcunningham** [comment]
Thanks for the quick reply. I've temporarily got around the issue by writing a `fromJson` class method on my `Test` class.

```
import 'package:json_god/json_god.dart' as god;

class Test {
  DateTime date;

  Test();

  factory Test.fromJson(Map<String, dynamic> test) =>
    new Test()..date = DateTime.parse(test["date"]);

}

void main() {
  //  god.debug = true;

  var test = new Test()..date = new DateTime(2017);
//    ..date = new DateTime(2017);

  print(test.date);

  String json = god.serialize(test);
  print(json);

  Test new_test = god.deserialize(json, outputType: Test);
  print(new_test.date);
}
```
I will take a look at TypedService.

Regards, Paul.
